import "./globals.css";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./components/Navbar";
import { CartProvider } from "./context/cart-context";

const inter = Poppins({
  weight: "300",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <CartProvider>
        <html lang="en">
          <body className={`${inter.className} h-screen`}>
            <Navbar />
            {children}
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
